[package]
name = "rocket"
version = "1.0.0"
authors = ["hyperchessbot <hyperchessbot@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.6"

[dependencies.rocket_contrib]
version = "0.4.6"
features = ["handlebars_templates", "tera_templates"]
